kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: legit-broker-cluster-role
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - legit-broker-psp
  verbs:
  - use

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: legit-broker-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "legit-broker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: legit-broker-cluster-role
  apiGroup: rbac.authorization.k8s.io