apiVersion: apps/v1
kind: Deployment
metadata:
  name: legit-kubernetes-agent
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubernetes-agent.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
            {{- include "kubernetes-agent.labels" . | nindent 8 }}
    spec:
      serviceAccountName: legit-kubernetes-agent-sa
      containers:
        - name: {{ .Chart.Name }}-broker
          image: "{{ .Values.image.broker.repository }}:{{ .Values.image.broker.tag }}"
          imagePullPolicy: {{ .Values.image.broker.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
           - name: BROKER_IDENTIFIER
             value: {{ required "A broker identifier value must be set!" .Values.legitBroker.identifier }}
           - name: BROKER_ENDPOINT
             value: {{ .Values.legitBroker.brokerEndpoint }}
          {{- if .Values.legitBroker.proxy }}
           - name: BROKER_PROXY
             value: {{ .Values.legitBroker.proxy }}
          {{- end }}
           
        - name: {{ .Chart.Name }}-proxy
          image: "{{ .Values.image.proxy.repository }}:{{ .Values.image.proxy.tag }}"
          imagePullPolicy: {{ .Values.image.proxy.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          