apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
type: Opaque
data:
  identifier: {{  required "A broker identifier value must be set!" .Values.agent.identifier }}
