name: Legit kubernetes agent 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: helm-lint
        run: |
          cd helm-chart \
          && helm lint . \
          && cd -
